version: '3'

services:
  registry:
    image: registry:2
    name: docker_registry
    restart: always
    ports:
    - "443:443"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - /etc/letsencrypt/live/docker.mediana.ir:/certs
      - /opt/docker-registry/data:/data
      - /opt/docker-registry/auth:/auth
